#Configura la máquina virtual del CI server, seleccionando SO, distribución y lenguaje de la app.
os:
- linux
dist: xenial
language: python
#Es lo que debe ejecutar el CI server, es decir, los Test Unitarios y el Code Coverage.
script:
- python -m pytest
- pytest --cov-report term --cov=./
#Configura el Deploy hacia Heroku
deploy:
  provider: heroku
  app: agiles-backend-2020
  api_key:
    secure: oxy0yRpNrfWE/5XDhjDlF5DchFIh8pjgKOa+wJXDiNccTBVDNoxFir5bgfmXIFaDw4R3zvC+GLV8wAz4dfSawoQXN9wK8gXitBtMN6zc1zrP92aU82NdsPAh11/6MPPpInNl99IiCHOSk5u+BTuVZJX0nz00c8ws2yMaTQEcqUW5Z/fpV2PkCxxzpf2J5IMkMZXbXOJkoj4ETOW6e1+Xqm8jL6Z+r/2EpwID+mJkVVopGV9n1qXqq9TXgKV0AqPXyTs2Rz6Hac4ADGUZB3HGGfcDMB6WYZY2nKAGkiW0j2trESVY9SF401FaAfF1gl9MfTh0nTCTSl6RoYu/BPUF/9aTym3jDdpqn1EZabVjJRBuqNNonajSnAtswPs0D04PFt9yf0B48cqgZJpxV5XYrTzS+j3/qhwjBfleJEQDDlcKv03bMOyfX2gGUU8/kvCSv7E91ZitPlySf78D1oomRkZMNrN/na552RqasuCSy4l03t/B+qhLVspUCq/N2W+QIN+ktXcRBGqJPMqe9JCa/IjIik7NrgHSeMjqjF3Do88nwsFPSvchaUnpyRxjirVFPrY4QBS+5QzxZV7Lsd5NBs5uTx7EwkYq/gl3kWmyAl3nLJEELzxW1TIHMo74DRchWT147+icAet39qzCRildyZp5dfJ5wsK7Wqlwhqkt6Ko=
#Se ejecuta solo si todo lo anterior fue exitoso (Tests y Deploy en Heroku).
after_success:
  #Envía estadisticas a CodeCov
  - bash <(curl -s https://codecov.io/bash)
  #
  - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
  - chmod +x trigger.sh
  - ./trigger.sh santiagogarcia97 TP-Agiles-2020-Frontend master $TRAVIS_ACCESS_TOKEN 
